#include <string>
#include <iostream>
#include <fstream>
#include <algorithm>
#include "GL/glew.h"
#include "../extra/picopng.h"
#include "utils.h"
#include "camera.h"
#include "mesh.h"
#include <cmath>
#include "image.h"